### ISSUE TITLE
[Bug]: 0.14 release broke formatter accepting file arguments

### ISSUE THREAD

**Issue by alexeagle** [aspect-build/rules_lint#169]
### What happened?

Due to https://github.com/keith/rules_multirun/issues/44
(and obviously missing integration testing in this repo)

### Version

0.14.0 and 0.14.1

### How to reproduce

```shell
INFO: Running command line: bazel-bin/tools/format/format.bash lint.sh
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_alexeagle/3eecd93732ac7c6f4f360a54a468da50/execroot/_main/bazel-out/darwin_arm64-fastbuild/bin/tools/format/format.bash.runfiles/_main/../rules_multirun~0.7.0/internal/multirun.py", line 91, in <module>
    _main(sys.argv[-1])
  File "/private/var/tmp/_bazel_alexeagle/3eecd93732ac7c6f4f360a54a468da50/execroot/_main/bazel-out/darwin_arm64-fastbuild/bin/tools/format/format.bash.runfiles/_main/../rules_multirun~0.7.0/internal/multirun.py", line 73, in _main
    with open(path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'lint.sh'
```

**Comment by alexeagle** [comment]
The bug is fixed by a rollback, leaving this open for the roll-forward

**Comment by hunshcn** [comment]
> The bug is fixed by a rollback, leaving this open for the roll-forward

it is time

**Comment by alexeagle** [comment]
Thanks @hunshcn , rolled forward in #182
