### ISSUE TITLE
[Bug]: Error: In js_library rule @@aspect_rules_lint~//lint:eslint.bazel-formatter, toolchain type @@aspect_bazel_lib~//lib:coreutils_toolchain_type was requested but only types [] are configured

### ISSUE THREAD

**Issue by Zemnmez** [aspect-build/rules_lint#192]
### What happened?

Linting to happen with no errors.

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`:
bazel 7.1.1

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:
bazel_dep(name = "aspect_rules_lint", version = "0.15.0")

Language(s) and/or frameworks involved:
Typescript + eslint.

### How to reproduce

1. Check out this commit: https://github.com/zemn-me/monorepo/pull/4966/commits/240f92b22a4a2159c132125cc50b2ef0a864fcd0
2. Run `bazel test //ts/math/...`

### Any other information?

Error:

```
WARNING: Option 'experimental_remote_build_event_upload' is deprecated: Use --remote_build_event_upload instead
INFO: Invocation ID: 54ecfcd1-fc0c-4485-9fba-98d5e9e9b454
INFO: Streaming build results to: https://app.buildbuddy.io/invocation/54ecfcd1-fc0c-4485-9fba-98d5e9e9b454
WARNING: Option 'experimental_remote_build_event_upload' is deprecated: Use --remote_build_event_upload instead
ERROR: /home/thomas/.cache/bazel/_bazel_thomas/a41610ee02ad9c69b13020a7f1cf3deb/external/aspect_rules_lint~/lint/BUILD.bazel:56:11: in js_library rule @@aspect_rules_lint~//lint:eslint.bazel-formatter: 
Traceback (most recent call last):
        File "/home/thomas/.cache/bazel/_bazel_thomas/a41610ee02ad9c69b13020a7f1cf3deb/external/aspect_rules_js~/js/private/js_library.bzl", line 167, column 61, in _js_library_impl
                sources, declarations = _gather_sources_and_declarations(
        File "/home/thomas/.cache/bazel/_bazel_thomas/a41610ee02ad9c69b13020a7f1cf3deb/external/aspect_rules_js~/js/private/js_library.bzl", line 127, column 46, in _gather_sources_and_declarations
                file = copy_js_file_to_bin_action(ctx, file)
        File "/home/thomas/.cache/bazel/_bazel_thomas/a41610ee02ad9c69b13020a7f1cf3deb/external/aspect_rules_js~/js/private/js_helpers.bzl", line 175, column 35, in copy_js_file_to_bin_action
                return copy_file_to_bin_action(ctx, file)
        File "/home/thomas/.cache/bazel/_bazel_thomas/a41610ee02ad9c69b13020a7f1cf3deb/external/aspect_bazel_lib~/lib/private/copy_to_bin.bzl", line 84, column 21, in copy_file_to_bin_action
                copy_file_action(ctx, file, dst)
        File "/home/thomas/.cache/bazel/_bazel_thomas/a41610ee02ad9c69b13020a7f1cf3deb/external/aspect_bazel_lib~/lib/private/copy_file.bzl", line 84, column 31, in copy_file_action
                coreutils = ctx.toolchains[_COREUTILS_TOOLCHAIN].coreutils_info
Error: In js_library rule @@aspect_rules_lint~//lint:eslint.bazel-formatter, toolchain type @@aspect_bazel_lib~//lib:coreutils_toolchain_type was requested but only types [] are configured
ERROR: /home/thomas/.cache/bazel/_bazel_thomas/a41610ee02ad9c69b13020a7f1cf3deb/external/aspect_rules_lint~/lint/BUILD.bazel:56:11: Analysis of target '@@aspect_rules_lint~//lint:eslint.bazel-formatter' failed
ERROR: Loading failed
Use --verbose_failures to see the command lines of failed build steps.
ERROR: Analysis of target '//ts/math/canvas:canvas_lint' failed; build aborted
INFO: Elapsed time: 0.216s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
ERROR: Build did NOT complete successfully
ERROR: No test targets were found, yet testing was requested
INFO: Streaming build results to: https://app.buildbuddy.io/invocation/54ecfcd1-fc0c-4485-9fba-98d5e9e9b454
```

**Comment by alexeagle** [comment]
This means you've somehow got an older version of rules_js than required. I think 1.34.0 is the minimum. If you're using WORKSPACE, you may need to fetch rules_js sooner, as some other initializer function might be fetching an old one.

**Comment by Zemnmez** [comment]
Thank you! I’ll give that a try :)ThomasOn 30 Mar 2024, at 15:58, Alex Eagle ***@***.***> wrote:﻿
This means you've somehow got an older version of rules_js than required. I think 1.34.0 is the minimum. If you're using WORKSPACE, you may need to fetch rules_js sooner, as some other initializer function might be fetching an old one.
