### ISSUE TITLE
[Bug]: aspect lint fails when using fail_on_validation in 1.0.0-rc3

### ISSUE THREAD

**Issue by ewhauser** [aspect-build/rules_lint#269]
### What happened?

Linters fail when using `fail_on_validation`:

```
Traceback (most recent call last):
        File "/private/var/tmp/_bazel_ewhauser/7f94d8e82ee14a19aaeabeb129bad8ac/external/aspect_rules_lint~override/lint/ruff.bzl", line 122, column 17, in _ruff_aspect_impl
                ruff_fix(ctx, ctx.executable, files_to_lint, ctx.files._config_files, patch, report, exit_code)
        File "/private/var/tmp/_bazel_ewhauser/7f94d8e82ee14a19aaeabeb129bad8ac/external/aspect_rules_lint~override/lint/ruff.bzl", line 105, column 58, in ruff_fix
                "JS_BINARY__EXIT_CODE_OUTPUT_FILE": exit_code.path,
Error: 'NoneType' value has no field or method 'path'
Use --verbose_failures to see the command lines of failed build steps.
```

### Version

1.0.0-rc3

### How to reproduce

```shell
Create a `.bazeliskrc` in `./examples`:


BAZELISK_BASE_URL=https://github.com/aspect-build/aspect-cli/releases/download
USE_BAZEL_VERSION=aspect/5.9.35
```

Add the following to `.bazelrc`:

```
common --@aspect_rules_lint//lint:fail_on_violation
```

Run:

bazel lint //...
```
```

**Comment by ewhauser** [comment]
@alexeagle Not sure if it is just me but I still see this issue when using the setting:

```
 common --@aspect_rules_lint//lint:fail_on_violation
```

in the `1.0+` versions. Having trouble figuring out a configuration to disable the `fix` config so I'm patching it out.
